version: "3.8"

volumes:
  redis: #docker volume create redis

networks:
  hipstershop:
    driver: bridge

# networks:
#   default:
#     external:
#       name: hipstershop  # docker network create hipstershop

services:
  frontend:
    image: srikanthhg/frontend:v1
    container_name: frontend
    ports:
    - "80:8080"
    depends_on:
    - productcatalogservice
    - currencyservice
    - cartservice
    - recommendationservice
    - checkoutservice
    - shippingservice
    - adservice

  productcatalogservice:
    image: srikanthhg/productcatalogservice:v1
    container_name: productcatalogservice

  currencyservice:
    image: srikanthhg/currencyservice:v1
    container_name: currencyservice

  cartservice:
    image: srikanthhg/cartservice:v1
    container_name: cartservice
    depends_on:
    - redis

  shippingservice:
    image: srikanthhg/shippingservice:v1
    container_name: shippingservice

  emailservice:
    image: srikanthhg/emailservice:v1
    container_name: emailservice

  checkoutservice:
    image: srikanthhg/checkoutservice:v1
    container_name: checkoutservice
    depends_on:
    - productcatalogservice
    - shippingservice
    - paymentservice
    - emailservice
    - currencyservice
    - cartservice

  recommendationservice:
    image: srikanthhg/recommendationservice:v1
    container_name: recommendationservice
    depends_on:
    - productcatalogservice

  adservice:
    image: srikanthhg/adservice:v1
    container_name: adservice

  paymentservice:
    image: srikanthhg/paymentservice:v1
    container_name: paymentservice
    
  redis:
    image: redis
    container_name: redis
    volumes: 
    - redis:/data

